### ISSUE TITLE
Query modifier `last` causes run not to be defined.

### ISSUE THREAD

**Issue by ardoramor** [trivialsoftware/trivialdb#34]
TrivialDb@2.3.0

The following code reports that `run` is not defined:

```
var db = require('trivialdb').db('test', {writeToDisk: false}};

db.query().sortBy('col').last().run();
```

The analogue code runs fine under lodash:

```
_.chain([]).sortBy('col').last().value();
```

Any ideas?

**Comment by Morgul** [comment]
Out of curiosity, does changing `.run()` to `.value()` make it work?

I'll look into this when I get a moment, and see if I can't run it down.

**Comment by ardoramor** [comment]
Yes, that was my first thought after I read the documentation. However, that doesn't work and results in the same error.

**Comment by Morgul** [comment]
@ardoramor Ah, I figured this out. It's a little tricky, and it's a question of which behavior I want.

According to the [lodash docs][ldchain]:

> Creates a lodash object which wraps value to enable implicit method chain sequences. Methods that operate on and return arrays, collections, and functions can be chained together. Methods that retrieve a single value or may return a primitive value will automatically end the chain sequence and return the unwrapped value. Otherwise, the value must be unwrapped with `_#value`.
>
> Explicit chain sequences, which must be unwrapped with `_#value`, may be enabled using `_.chain`.

I am not using `_.chain`. (See [here][query].) Instead I'm using the implicit chaining, because that's how I prefer to do things in my other projects that use lodash.

For now, the workaround is to leave off `.run()`. However, I can see the point here; this is emulating a database API; explicit chaining the most expected behavior. It should be a small, but breaking change. (Technically, I think it would force me to v3.0.0. That's unfortunate.)

I _could_ allow you to pass in an option to specify that you want explicit chaining behavior. That would allow me to keep it a minor version change. Would that be acceptable? And, would you want that option on the database, on `query()`, or both?

[ldchain]: https://lodash.com/docs/4.17.4#lodash
[query]: https://github.com/trivialsoftware/trivialdb/blob/master/lib/tdb.js#L261-L269

**Comment by ardoramor** [comment]
Hmm, that is a good point. I actually changed my code to:
```
var db = require('trivialdb').db('test', {writeToDisk: false}};
var list = db.query().sortBy('col').run();
var last = list[list.length - 1]; 
```
So I am already using a workaround. Honestly, I would suggest moving towards a desired API. If it has to be released in v3.0.0 with a wait, I think it is fine as long as README mentions a caveat of `query` so as not to throw off other devs.

**Comment by Morgul** [comment]
@ardoramor I'm going to keep this open for the history, but I've pushed a documentation change.

**Comment by Morgul** [comment]
@ardoramor Sorry it's taken so long, but v3.0.0 is published. (The rc's had been out for a long time, but I finally decided it was time to cut the real release.)
